[package]
name = "sui-client-gen"
version = "0.3.2"
edition = "2021"

[dependencies]
tokio = "^1.36.0"
anyhow = "^1.0.71"
futures = "^0.3.28"
tempfile = "^3.5.0"
toml = { version = "0.5.11", features = ["preserve_order"] }
regex = "^1.8.1"
genco = "^0.17.8"
clap = "^4.4"
codespan-reporting = "^0.11.1"
convert_case = "^0.6.0"
colored = "^2.0.0"

sui-move-build = { git = "https://github.com/MystenLabs/sui", rev = "3f1540b" }
sui-move = { git = "https://github.com/MystenLabs/sui", rev = "3f1540b" }
sui-sdk = { git = "https://github.com/MystenLabs/sui", rev = "3f1540b" }
sui-json-rpc-types = { git = "https://github.com/MystenLabs/sui", rev = "3f1540b" }
move-model = { git = "https://github.com/MystenLabs/sui", rev = "3f1540b" }
move-core-types = { git = "https://github.com/MystenLabs/sui", rev = "3f1540b" }
move-binary-format = { git = "https://github.com/MystenLabs/sui", rev = "3f1540b" }
move-symbol-pool = { git = "https://github.com/MystenLabs/sui", rev = "3f1540b" }
move-bytecode-utils = { git = "https://github.com/MystenLabs/sui", rev = "3f1540b" }
move-compiler = { git = "https://github.com/MystenLabs/sui", rev = "3f1540b" }
move-package = { git = "https://github.com/MystenLabs/sui", rev = "3f1540b" }
move-command-line-common = { git = "https://github.com/MystenLabs/sui", rev = "3f1540b" }
